In [1]:
import tensorflow as tf

ta = tf.zeros((2, 2)) # 2행 2열

session = tf.InteractiveSession()
print(ta.eval())
session.close()

[[0. 0.]
 [0. 0.]]


In [2]:
# Graph를 먼저 만들어서 데이터 흐름을 표현한다

# 앞서 실행했던 세션의 그래프를 리셋
tf.reset_default_graph()
# 두 개의 수를 곱하는 데이터의 흐름을 그래프로 만들어본다
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")

mul_op = tf.multiply(a, b)


# 실행,  그래프를 직접 시각화
with tf.Session() as sess:
    # 그래프 시각화 위해 로그 정보 기록
    tf.summary.FileWriter("d:/log_dir", graph=sess.graph)
    print("a*b", sess.run(mul_op)) # 실제 연산은 세션에서

a*b 600


In [3]:
#변수와 상수
# 상수: tf.constant
# 변수: tf.Variable -> tf.global_variabes_initializer로 초기화
hello = tf.constant("Hello, Tensorflow")
w1 = tf.zeros((3, 3)) 
var1 = tf.Variable(tf.zeros((2, 2)), name="weights")
# 2행2열의 0ㅇ로 채워진 텐서
node1 = tf.constant(3.0, dtype=tf.float32) #dtype으로 텐서의 내부 데이터 타입을 설정
node2 = tf.constant(4.0) # dtype 생략 -> tf,float32타입으로 결정

with tf.Session() as sess:
    # 변수가 있을 경우 초기화 수행
    sess.run(tf.global_variables_initializer()) # 변수의 초기화
    print(sess.run(w1))
    print(sess.run(var1))
    print(node1.eval())
    print(node2.eval())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
3.0
4.0


In [4]:
# Graph의 생성
# session
# Tensor: Data
# Tensorflow: 데이터의 플로우
# 개별적으로 연산 수행하는 것이 아니라 데이터의 흐름을 그래프로 표현한 이후 실제 연산은 Session에서 수행
tf.reset_default_graph() # 그래프 초기화

a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
add_op = tf.add(a, b, name="add")

with tf.Session() as sess:
    tf.summary.FileWriter("d:/log_dir", graph=sess.graph)
    print("실제 연산의 수행:", sess.run(add_op))

실제 연산의 수행: 5


In [5]:
# 변수
# 변수는 저장 및 변경이 가능
# 텐서플로의 초기화 메서드로 할당 및 변경 가능
tf.reset_default_graph()

s1 = tf.get_variable(name="scalar1", initializer=1) #
s2 = tf.get_variable(name="scalar2", initializer=tf.constant(2))
m = tf.get_variable(name="matrix", initializer=tf.constant([
    [0, 1],
    [2, 3]
]))
M = tf.get_variable(name="big_matrix",
                   shape=(784, 10),
                    initializer= tf.truncated_normal_initializer(
                    mean=0.0, stddev=0.01))

# 변수는 항상 초기화 연산을 먼저 수행해야 한다
init_op = tf.global_variables_initializer() # 초기화

with tf.Session() as sess:
    tf.summary.FileWriter("d:/log_dir", graph=sess.graph)
    # 변수 초기화
    sess.run(init_op)
    print("scala 변수:", sess.run(s1), s1)
    print("scala 변수2:", sess.run(s2), s2)
    print("matrix 변수:", sess.run(m), m)
    print("분포를 이용한 matrix 변수의 초기화:", sess.run(M), M)

scala 변수: 1 <tf.Variable 'scalar1:0' shape=() dtype=int32_ref>
scala 변수2: 2 <tf.Variable 'scalar2:0' shape=() dtype=int32_ref>
matrix 변수: [[0 1]
 [2 3]] <tf.Variable 'matrix:0' shape=(2, 2) dtype=int32_ref>
분포를 이용한 matrix 변수의 초기화: [[ 0.01175605  0.01031111  0.00861976 ... -0.00324447 -0.01116965
   0.01551179]
 [ 0.00659956  0.00242709 -0.00815523 ...  0.00395405  0.00979263
   0.01161216]
 [-0.00205083  0.0077141   0.00926358 ...  0.00288189 -0.00420392
   0.00928708]
 ...
 [-0.01685472  0.00033433 -0.00284041 ...  0.00366753  0.00244239
   0.01469059]
 [ 0.00244791  0.00817177  0.01025681 ... -0.01357173 -0.00763388
  -0.0008214 ]
 [ 0.00469538  0.00524509 -0.00833911 ...  0.01785381 -0.00267503
   0.00974486]] <tf.Variable 'big_matrix:0' shape=(784, 10) dtype=float32_ref>


In [6]:
# Placeholder
# 값 혹은 사이즈 미정, 실행되는 시점에서 값이 결정되는 데이터 타입
tf.reset_default_graph()

a = tf.placeholder(tf.float32, shape=[5]) # 1차원 텐서
b = tf.placeholder(tf.float32) # shape가 지정되지 않은 이름 없는 텐서
x = tf.placeholder(tf.float32, shape=[None, 784], name="input")
# 열의 개수는 784개 행의개수가 미정인 이름이 input인 2차원 텐서
y = tf.placeholder(tf.float32, shape=[None, 10], name="label")
# 열의 개수는 10개 행의 개수가 미정인 이름이 label인 2차원 텐서

a = tf.constant([5, 5, 5], tf.float32, name="A") # 3열의 1차원 상수 텐서
b = tf.placeholder(tf.float32, shape=[3], name="B") # 3열의 1차원 플레이스홀더
c = tf.add(a, b, name="Add")
with tf.Session() as sess:
    # placeholder에 실행 시점에서 데이터를 전달하고자 한다면 사전을 만들어 전달할 수 있다
    d = {b: [1, 2, 3]}
    # placeholder에 사전을 전달해서 수행
    print("Add with Placeholder:", sess.run(c, feed_dict=d))
    # feed_dict인자로 사전을 전달

Add with Placeholder: [6. 7. 8.]


In [7]:
# 책 공부

In [17]:
import tensorflow as tf
hello = tf.constant("Hello, Tensorflow")
print(hello)

a = tf.constant(10, name="studya")
b = tf.constant(20, name="studyb")
c = tf.add(a, b)
print(c)

with tf.Session() as sess:
    print(sess.run(hello))
    print(sess.run(c))

Tensor("Const_9:0", shape=(), dtype=string)
Tensor("Add_8:0", shape=(), dtype=int32)
b'Hello, Tensorflow'
30
